Adds Trends Service Request
discovery-tecnologia/dsc-mercado-livre pull request #81
Opened 2021-04-18 22:33 UTC by rafa-acioly

Adds trends service

2021-04-19 00:32 UTC, dilowagner approved these changes
@rafa-acioly 
Cara, mais uma vez muito obrigado pela contribuicao! :+1:

2021-04-19 00:34 UTC, dilowagner requested changes
Acabei vendo agora que tivemos uma falha nos testes unitarios hehe

2021-04-19 00:36 UTC, dilowagner commented
@rafa-acioly 
Voce precisa importar a class Annotation as JMS para usar a anotacao com JMS

```php
use JMS\Serializer\Annotation as JMS;
```

2021-04-19 22:59 UTC, rafa-acioly commented
@dilowagner já era tarde da noite, acabei deixando passar! rs

2021-04-20 02:07 UTC, dilowagner approved these changes

2021-04-20 02:08 UTC, merged

2021-04-20 02:13 UTC, dilowagner commented
Nova [Versão 2.3.0](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/2.3.0) gerada!

Valeu @rafa-acioly mais uma vez pela ajuda! :+1: